# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f35ecaa455ccacb3378331fbef95b144223a886b99f790ee009fc267adf317533e8cd55f46b574ee7ed3721cfe559b4ee77aa17851c0135e42bffc130461349

test:
  secret_key_base: 99cc894e6d4800a1972320ee40202faead18cabb054a4098cada6d8a9efdb5d17e67e29a048cfee5abe60155da7fc22591a8ece0e7c0fb096f05e30ebbfec75f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
